# Generated by Django 4.0.4 on 2022-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0002_contactus_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ac_service_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phno', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('dos', models.DateField()),
                ('purpose', models.TextField()),
                ('flag', models.CharField(max_length=8)),
            ],
        ),
    ]
