# Generated by Django 3.2.9 on 2022-04-26 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0004_skater_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skater_registrations',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
