# Generated by Django 3.2.9 on 2022-04-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0005_alter_skater_registrations_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skater_registrations',
            name='photo',
        ),
    ]
