# Generated by Django 3.2.9 on 2022-04-28 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0006_remove_skater_registrations_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater_registrations',
            name='branch',
            field=models.CharField(default=datetime.datetime(2022, 4, 28, 6, 10, 51, 891251, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
