# Generated by Django 3.2.9 on 2022-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0007_skater_registrations_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skater_registrations',
            name='address',
            field=models.TextField(unique=True),
        ),
    ]
