# Generated by Django 3.2.9 on 2022-04-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0008_alter_skater_registrations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skater_registrations',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='skater_registrations',
            name='address',
            field=models.TextField(),
        ),
    ]
