# Generated by Django 3.2.9 on 2022-04-28 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0009_auto_20220428_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater_registrations',
            name='outsider',
            field=models.CharField(default=datetime.datetime(2022, 4, 28, 6, 27, 46, 265887, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
