# Generated by Django 3.2.9 on 2022-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0010_skater_registrations_outsider'),
    ]

    operations = [
        migrations.CreateModel(
            name='dancer_registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('fname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('doj', models.DateField()),
                ('branch', models.CharField(max_length=50)),
                ('outsider', models.CharField(max_length=10)),
            ],
        ),
    ]
